### ISSUE TITLE
What is randomFloat range? It is not [0, 1)

### ISSUE THREAD

**Issue by bugcaptor** [iskolbin/mt#1]
I assumed randomFloat range is [0.0, 1.0) but it never goes near 1.0 even near 0.5..

**Comment by iskolbin** [comment]
Hi, randomFloat range is indeed [0.0,1.0). But as we are talking about Haxe the complier version and target matters:). What complier are you using? What target is? I recently updated library and added tests directly from original source by authors. 

On my iMac 27 i5 2.9 Ghz late 2012 Sierra 10.12.1, using Haxe 3.3 I've got the following results:

cpp, cs, java, swf, js, neko -- passes all tests
python, lua -- passes half of the tests
php -- broken
hl -- not tested at all

Hope that helps:)

**Comment by bugcaptor** [comment]
I tested on Windows 10 pro 64bit. Haxe version is 3.2.1. Targets were windows and html.
Maybe haxe version is the problem. Probably for this issue https://github.com/HaxeFoundation/haxe/issues/2736 ? I will test upgraded haxe environment. Thanks for reply.

**Comment by iskolbin** [comment]
You are welcome. Just in case there are tests in the folder `test32.hxml` (without Lua target) and `test33.hxml` you can run them using `haxe <testfile>` and see results.

**Comment by bugcaptor** [comment]
I upgraded to haxe 3.3.0 rc1 and it works! Thanks!

**Comment by iskolbin** [comment]
Glad to hear:)
